/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MatchmakingRouteImport } from './routes/matchmaking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges.index'
import { Route as ChallengesNewRouteImport } from './routes/challenges.new'
import { Route as ChallengesIdRouteImport } from './routes/challenges.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakingRoute = MatchmakingRouteImport.update({
  id: '/matchmaking',
  path: '/matchmaking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesNewRoute = ChallengesNewRouteImport.update({
  id: '/challenges/new',
  path: '/challenges/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdRoute = ChallengesIdRouteImport.update({
  id: '/challenges/$id',
  path: '/challenges/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/fraud': typeof FraudRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/matchmaking': typeof MatchmakingRoute
  '/notifications': typeof NotificationsRoute
  '/results': typeof ResultsRoute
  '/venues': typeof VenuesRoute
  '/wallet': typeof WalletRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/new': typeof ChallengesNewRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/fraud': typeof FraudRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/matchmaking': typeof MatchmakingRoute
  '/notifications': typeof NotificationsRoute
  '/results': typeof ResultsRoute
  '/venues': typeof VenuesRoute
  '/wallet': typeof WalletRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/new': typeof ChallengesNewRoute
  '/challenges': typeof ChallengesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/fraud': typeof FraudRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/login': typeof LoginRoute
  '/matchmaking': typeof MatchmakingRoute
  '/notifications': typeof NotificationsRoute
  '/results': typeof ResultsRoute
  '/venues': typeof VenuesRoute
  '/wallet': typeof WalletRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/new': typeof ChallengesNewRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkin'
    | '/fraud'
    | '/leaderboards'
    | '/login'
    | '/matchmaking'
    | '/notifications'
    | '/results'
    | '/venues'
    | '/wallet'
    | '/challenges/$id'
    | '/challenges/new'
    | '/challenges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkin'
    | '/fraud'
    | '/leaderboards'
    | '/login'
    | '/matchmaking'
    | '/notifications'
    | '/results'
    | '/venues'
    | '/wallet'
    | '/challenges/$id'
    | '/challenges/new'
    | '/challenges'
  id:
    | '__root__'
    | '/'
    | '/checkin'
    | '/fraud'
    | '/leaderboards'
    | '/login'
    | '/matchmaking'
    | '/notifications'
    | '/results'
    | '/venues'
    | '/wallet'
    | '/challenges/$id'
    | '/challenges/new'
    | '/challenges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  FraudRoute: typeof FraudRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  LoginRoute: typeof LoginRoute
  MatchmakingRoute: typeof MatchmakingRoute
  NotificationsRoute: typeof NotificationsRoute
  ResultsRoute: typeof ResultsRoute
  VenuesRoute: typeof VenuesRoute
  WalletRoute: typeof WalletRoute
  ChallengesIdRoute: typeof ChallengesIdRoute
  ChallengesNewRoute: typeof ChallengesNewRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaking': {
      id: '/matchmaking'
      path: '/matchmaking'
      fullPath: '/matchmaking'
      preLoaderRoute: typeof MatchmakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/new': {
      id: '/challenges/new'
      path: '/challenges/new'
      fullPath: '/challenges/new'
      preLoaderRoute: typeof ChallengesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id': {
      id: '/challenges/$id'
      path: '/challenges/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  FraudRoute: FraudRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  LoginRoute: LoginRoute,
  MatchmakingRoute: MatchmakingRoute,
  NotificationsRoute: NotificationsRoute,
  ResultsRoute: ResultsRoute,
  VenuesRoute: VenuesRoute,
  WalletRoute: WalletRoute,
  ChallengesIdRoute: ChallengesIdRoute,
  ChallengesNewRoute: ChallengesNewRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
